FROM nginx:stable

# install packages
RUN apt-get update && \
    apt-get install -y openssl bash curl vim && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
    
# config & certs
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/api-community-nginx.conf /etc/nginx/conf.d/api-community-nginx.conf
# COPY ./docker/nginx/server.crt /etc/nginx/ssl/server.crt
# COPY ./docker/nginx/server.key /etc/nginx/ssl/server.key

# run on build
# COPY ./docker/nginx/decrypt-server-key.sh /usr/local/bin/decrypt-server-key.sh
# RUN chmod +x /usr/local/bin/decrypt-server-key.sh

# run on runtime
# CMD ["/usr/local/bin/decrypt-server-key.sh"]

EXPOSE 80 81 443

WORKDIR /var/www/html